services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust # Hinzugefügt: Authentifizierung auf "trust" setzen (NUR FÜR ENTWICKLUNG!)
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork: