version: '3.8'

services:
  frontend:
    image: yaceybln/my-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    args:
      VITE_API_URL: "/api"
    ports:
      - "8080:80"
    depends_on:
      - backend
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend

  backend:
    image: yaceybln/my-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: myuser
      DB_NAME: mydb
      DB_PASSWORD: mypassword
      PORT: 3000
    healthcheck:
      test: curl -f http://localhost:3000/api/health/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      placement:
        constraints:
          - node.labels.role == backend

  database:
    image: postgres:17-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      placement:
        constraints:
          - node.labels.role == database

volumes:
  db_data:
