apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.backend.database.password | b64enc }}
  API_KEY: {{ .Values.backend.apiKey | b64enc }}